<?php include('head.php');
if(isset($_POST['register'])){
    $pseudo = $_POST['username'];
    $_SESSION['name_user'] = $pseudo;
    require_once("./class/User.php");
    $user = new User();
    $password = password_hash($_POST['password'], PASSWORD_DEFAULT);
    $name = $_POST['nom'];
    $email = $_POST['email'];
    $bio = $_POST['bio'];

    $fileName = $_FILES['profilePic']['name'];
    $fileTmpName = $_FILES['profilePic']['tmp_name'];
    $fileSize = $_FILES['profilePic']['size'];
    $fileError = $_FILES['profilePic']['error'];
    $fileType = $_FILES['profilePic']['type'];

    $fileExt = explode('.',$fileName);
    $fileActualExt = strtolower(end($fileExt));
    $allowed = array('jpg','png','gif');

    if (in_array($fileActualExt,$allowed )) {
        if ($fileError === 0) {
            if ($fileSize < 100000000) {
                $picture = base64_encode(file_get_contents(addslashes($fileTmpName)));
            }
        }
    } 
    else{
        $picture = "/9j/4AAQSkZJRgABAQEBLAEsAAD/4QB1RXhpZgAASUkqAAgAAAACAA4BAgBHAAAAJgAAABIBAwABAAAAAQAAAAAAAABEZWZhdWx0IHByb2ZpbGUgcGljdHVyZSwgYXZhdGFyLCBwaG90byBwbGFjZWhvbGRlci4gVmVjdG9yIGlsbHVzdHJhdGlvbv/hBWtodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+Cjx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iPgoJPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KCQk8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtbG5zOklwdGM0eG1wQ29yZT0iaHR0cDovL2lwdGMub3JnL3N0ZC9JcHRjNHhtcENvcmUvMS4wL3htbG5zLyIgICB4bWxuczpHZXR0eUltYWdlc0dJRlQ9Imh0dHA6Ly94bXAuZ2V0dHlpbWFnZXMuY29tL2dpZnQvMS4wLyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpwbHVzPSJodHRwOi8vbnMudXNlcGx1cy5vcmcvbGRmL3htcC8xLjAvIiAgeG1sbnM6aXB0Y0V4dD0iaHR0cDovL2lwdGMub3JnL3N0ZC9JcHRjNHhtcEV4dC8yMDA4LTAyLTI5LyIgeG1sbnM6eG1wUmlnaHRzPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgcGhvdG9zaG9wOkNyZWRpdD0iR2V0dHkgSW1hZ2VzL2lTdG9ja3Bob3RvIiBHZXR0eUltYWdlc0dJRlQ6QXNzZXRJRD0iMTIyMzY3MTM5MiIgeG1wUmlnaHRzOldlYlN0YXRlbWVudD0iaHR0cHM6Ly93d3cuaXN0b2NrcGhvdG8uY29tL2xlZ2FsL2xpY2Vuc2UtYWdyZWVtZW50P3V0bV9tZWRpdW09b3JnYW5pYyZhbXA7dXRtX3NvdXJjZT1nb29nbGUmYW1wO3V0bV9jYW1wYWlnbj1pcHRjdXJsIiA+CjxkYzpjcmVhdG9yPjxyZGY6U2VxPjxyZGY6bGk+Y3VtYWNyZWF0aXZlPC9yZGY6bGk+PC9yZGY6U2VxPjwvZGM6Y3JlYXRvcj48ZGM6ZGVzY3JpcHRpb24+PHJkZjpBbHQ+PHJkZjpsaSB4bWw6bGFuZz0ieC1kZWZhdWx0Ij5EZWZhdWx0IHByb2ZpbGUgcGljdHVyZSwgYXZhdGFyLCBwaG90byBwbGFjZWhvbGRlci4gVmVjdG9yIGlsbHVzdHJhdGlvbjwvcmRmOmxpPjwvcmRmOkFsdD48L2RjOmRlc2NyaXB0aW9uPgo8cGx1czpMaWNlbnNvcj48cmRmOlNlcT48cmRmOmxpIHJkZjpwYXJzZVR5cGU9J1Jlc291cmNlJz48cGx1czpMaWNlbnNvclVSTD5odHRwczovL3d3dy5pc3RvY2twaG90by5jb20vcGhvdG8vbGljZW5zZS1nbTEyMjM2NzEzOTItP3V0bV9tZWRpdW09b3JnYW5pYyZhbXA7dXRtX3NvdXJjZT1nb29nbGUmYW1wO3V0bV9jYW1wYWlnbj1pcHRjdXJsPC9wbHVzOkxpY2Vuc29yVVJMPjwvcmRmOmxpPjwvcmRmOlNlcT48L3BsdXM6TGljZW5zb3I+CgkJPC9yZGY6RGVzY3JpcHRpb24+Cgk8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJ3Ij8+Cv/iDFhJQ0NfUFJPRklMRQABAQAADEhMaW5vAhAAAG1udHJSR0IgWFlaIAfOAAIACQAGADEAAGFjc3BNU0ZUAAAAAElFQyBzUkdCAAAAAAAAAAAAAAAAAAD21gABAAAAANMtSFAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEWNwcnQAAAFQAAAAM2Rlc2MAAAGEAAAAbHd0cHQAAAHwAAAAFGJrcHQAAAIEAAAAFHJYWVoAAAIYAAAAFGdYWVoAAAIsAAAAFGJYWVoAAAJAAAAAFGRtbmQAAAJUAAAAcGRtZGQAAALEAAAAiHZ1ZWQAAANMAAAAhnZpZXcAAAPUAAAAJGx1bWkAAAP4AAAAFG1lYXMAAAQMAAAAJHRlY2gAAAQwAAAADHJUUkMAAAQ8AAAIDGdUUkMAAAQ8AAAIDGJUUkMAAAQ8AAAIDHRleHQAAAAAQ29weXJpZ2h0IChjKSAxOTk4IEhld2xldHQtUGFja2FyZCBDb21wYW55AABkZXNjAAAAAAAAABJzUkdCIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAAEnNSR0IgSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAA81EAAQAAAAEWzFhZWiAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAkoAAAD4QAALbPZGVzYwAAAAAAAAAWSUVDIGh0dHA6Ly93d3cuaWVjLmNoAAAAAAAAAAAAAAAWSUVDIGh0dHA6Ly93d3cuaWVjLmNoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRlc2MAAAAAAAAALklFQyA2MTk2Ni0yLjEgRGVmYXVsdCBSR0IgY29sb3VyIHNwYWNlIC0gc1JHQgAAAAAAAAAAAAAALklFQyA2MTk2Ni0yLjEgRGVmYXVsdCBSR0IgY29sb3VyIHNwYWNlIC0gc1JHQgAAAAAAAAAAAAAAAAAAAAAAAAAAAABkZXNjAAAAAAAAACxSZWZlcmVuY2UgVmlld2luZyBDb25kaXRpb24gaW4gSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAAsUmVmZXJlbmNlIFZpZXdpbmcgQ29uZGl0aW9uIGluIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdmlldwAAAAAAE6T+ABRfLgAQzxQAA+3MAAQTCwADXJ4AAAABWFlaIAAAAAAATAlWAFAAAABXH+dtZWFzAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAACjwAAAAJzaWcgAAAAAENSVCBjdXJ2AAAAAAAABAAAAAAFAAoADwAUABkAHgAjACgALQAyADcAOwBAAEUASgBPAFQAWQBeAGMAaABtAHIAdwB8AIEAhgCLAJAAlQCaAJ8ApACpAK4AsgC3ALwAwQDGAMsA0ADVANsA4ADlAOsA8AD2APsBAQEHAQ0BEwEZAR8BJQErATIBOAE+AUUBTAFSAVkBYAFnAW4BdQF8AYMBiwGSAZoBoQGpAbEBuQHBAckB0QHZAeEB6QHyAfoCAwIMAhQCHQImAi8COAJBAksCVAJdAmcCcQJ6AoQCjgKYAqICrAK2AsECywLVAuAC6wL1AwADCwMWAyEDLQM4A0MDTwNaA2YDcgN+A4oDlgOiA64DugPHA9MD4APsA/kEBgQTBCAELQQ7BEgEVQRjBHEEfgSMBJoEqAS2BMQE0wThBPAE/gUNBRwFKwU6BUkFWAVnBXcFhgWWBaYFtQXFBdUF5QX2BgYGFgYnBjcGSAZZBmoGewaMBp0GrwbABtEG4wb1BwcHGQcrBz0HTwdhB3QHhgeZB6wHvwfSB+UH+AgLCB8IMghGCFoIbgiCCJYIqgi+CNII5wj7CRAJJQk6CU8JZAl5CY8JpAm6Cc8J5Qn7ChEKJwo9ClQKagqBCpgKrgrFCtwK8wsLCyILOQtRC2kLgAuYC7ALyAvhC/kMEgwqDEMMXAx1DI4MpwzADNkM8w0NDSYNQA1aDXQNjg2pDcMN3g34DhMOLg5JDmQOfw6bDrYO0g7uDwkPJQ9BD14Peg+WD7MPzw/sEAkQJhBDEGEQfhCbELkQ1xD1ERMRMRFPEW0RjBGqEckR6BIHEiYSRRJkEoQSoxLDEuMTAxMjE0MTYxODE6QTxRPlFAYUJxRJFGoUixStFM4U8BUSFTQVVhV4FZsVvRXgFgMWJhZJFmwWjxayFtYW+hcdF0EXZReJF64X0hf3GBsYQBhlGIoYrxjVGPoZIBlFGWsZkRm3Gd0aBBoqGlEadxqeGsUa7BsUGzsbYxuKG7Ib2hwCHCocUhx7HKMczBz1HR4dRx1wHZkdwx3sHhYeQB5qHpQevh7pHxMfPh9pH5Qfvx/qIBUgQSBsIJggxCDwIRwhSCF1IaEhziH7IiciVSKCIq8i3SMKIzgjZiOUI8Ij8CQfJE0kfCSrJNolCSU4JWgllyXHJfcmJyZXJocmtyboJxgnSSd6J6sn3CgNKD8ocSiiKNQpBik4KWspnSnQKgIqNSpoKpsqzysCKzYraSudK9EsBSw5LG4soizXLQwtQS12Last4S4WLkwugi63Lu4vJC9aL5Evxy/+MDUwbDCkMNsxEjFKMYIxujHyMioyYzKbMtQzDTNGM38zuDPxNCs0ZTSeNNg1EzVNNYc1wjX9Njc2cjauNuk3JDdgN5w31zgUOFA4jDjIOQU5Qjl/Obw5+To2OnQ6sjrvOy07azuqO+g8JzxlPKQ84z0iPWE9oT3gPiA+YD6gPuA/IT9hP6I/4kAjQGRApkDnQSlBakGsQe5CMEJyQrVC90M6Q31DwEQDREdEikTORRJFVUWaRd5GIkZnRqtG8Ec1R3tHwEgFSEtIkUjXSR1JY0mpSfBKN0p9SsRLDEtTS5pL4kwqTHJMuk0CTUpNk03cTiVObk63TwBPSU+TT91QJ1BxULtRBlFQUZtR5lIxUnxSx1MTU19TqlP2VEJUj1TbVShVdVXCVg9WXFapVvdXRFeSV+BYL1h9WMtZGllpWbhaB1pWWqZa9VtFW5Vb5Vw1XIZc1l0nXXhdyV4aXmxevV8PX2Ffs2AFYFdgqmD8YU9homH1YklinGLwY0Njl2PrZEBklGTpZT1lkmXnZj1mkmboZz1nk2fpaD9olmjsaUNpmmnxakhqn2r3a09rp2v/bFdsr20IbWBtuW4SbmtuxG8eb3hv0XArcIZw4HE6cZVx8HJLcqZzAXNdc7h0FHRwdMx1KHWFdeF2Pnabdvh3VnezeBF4bnjMeSp5iXnnekZ6pXsEe2N7wnwhfIF84X1BfaF+AX5ifsJ/I3+Ef+WAR4CogQqBa4HNgjCCkoL0g1eDuoQdhICE44VHhauGDoZyhteHO4efiASIaYjOiTOJmYn+imSKyoswi5aL/IxjjMqNMY2Yjf+OZo7OjzaPnpAGkG6Q1pE/kaiSEZJ6kuOTTZO2lCCUipT0lV+VyZY0lp+XCpd1l+CYTJi4mSSZkJn8mmia1ZtCm6+cHJyJnPedZJ3SnkCerp8dn4uf+qBpoNihR6G2oiailqMGo3aj5qRWpMelOKWpphqmi6b9p26n4KhSqMSpN6mpqhyqj6sCq3Wr6axcrNCtRK24ri2uoa8Wr4uwALB1sOqxYLHWskuywrM4s660JbSctRO1irYBtnm28Ldot+C4WbjRuUq5wro7urW7LrunvCG8m70VvY++Cr6Evv+/er/1wHDA7MFnwePCX8Lbw1jD1MRRxM7FS8XIxkbGw8dBx7/IPci8yTrJuco4yrfLNsu2zDXMtc01zbXONs62zzfPuNA50LrRPNG+0j/SwdNE08bUSdTL1U7V0dZV1tjXXNfg2GTY6Nls2fHadtr724DcBdyK3RDdlt4c3qLfKd+v4DbgveFE4cziU+Lb42Pj6+Rz5PzlhOYN5pbnH+ep6DLovOlG6dDqW+rl63Dr++yG7RHtnO4o7rTvQO/M8Fjw5fFy8f/yjPMZ86f0NPTC9VD13vZt9vv3ivgZ+Kj5OPnH+lf65/t3/Af8mP0p/br+S/7c/23////tAJZQaG90b3Nob3AgMy4wADhCSU0EBAAAAAAAehwCUAAMY3VtYWNyZWF0aXZlHAJ4AEdEZWZhdWx0IHByb2ZpbGUgcGljdHVyZSwgYXZhdGFyLCBwaG90byBwbGFjZWhvbGRlci4gVmVjdG9yIGlsbHVzdHJhdGlvbhwCbgAYR2V0dHkgSW1hZ2VzL2lTdG9ja3Bob3Rv/9sAQwACAQEBAQECAQEBAgICAgIEAwICAgIFBAQDBAYFBgYGBQYGBgcJCAYHCQcGBggLCAkKCgoKCgYICwwLCgwJCgoK/9sAQwECAgICAgIFAwMFCgcGBwoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoK/8AAEQgBoAGgAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A/fiiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKK4f4tfH7wL8JIjaalOb7VWTdDpNow8zkcNIeka9OTyewOKAO4xnpXNeLvjD8L/AkjW/inxvYW06H57VZfNmX6xxhnH5V8ufEX9o/4pfEV5LebWm0vT2yBp2lOY1K+juPnk46gkKf7orglREGEUAewqlEnmPqXVv21vhTYu0emaRrd+R92SK0SND/38cMP++axJv26tJD4tvhpdsvYyamin8ghr52op2Qrs+iYf26tJL4ufhpdqvcx6mjH8igrb0n9tb4U3zrFqeka3YE/ekltEkQf9+3LH/vmvluiiyC7PuDwj8Yfhf47kW38K+N7C5nc4S1aTypm+kcgVz+VdJjHWvz6ZEcYdQR7iu9+HX7R/wAUvh08dtBrTapp64B07VHMihfRH+/Hx0AJUf3TS5R8x9kUVw/wk+P3gb4uRC006c2OqqmZtJu2HmcDloz0kXryOR3AzXcVJQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFeZ/tLfG3/hVXhldH0Cdf7d1RGFp0P2WLo05Hr2UHgtzyFIoAxP2jf2mB4HeXwJ8P7hJNZ27b2+wGSxyPugdGlx68L3yeK+Zbq5ur66lvr66knnnkLzzzOWeRzyWZjySfU02SSSWRpppWd3YtJI7EszE5JJPUk85pKtKxDdwooopiCiiigAooooAKKKKAH2tzdWN1FfWN1JBPBIHgnhcq8bjkMrDkEeor6a/Zz/AGmB44ki8CfEC4SPWduLK+wFS+x/CQOFlx2HDdsHivmKljkkikWaGVo3Rg0ciMQysDkEEcgg85pNXGnY/QOivM/2afjb/wALU8Mto+vzr/buloou+32qLos4Hr2YDgNzwGAr0yoLCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAKut61pvhzRrvxBrFwIbSyt3nuZD/AAooJJ9+B0r4e+IXjnVfiT4yvvGesZWS7l/cwk5EEI4SIf7q9fU5PU179+2t48bSvCdj8PrGbEurzefegHpbxEEKf96Taf8Atmwr5oqoomTCiiiqJCiiigAooooAKKKKACiiigAooooA2fh7451X4b+MrHxno+WktJP30IOBPCeHiP8AvL09Dg9RX3Domtab4j0a08QaPcCW0vbdJ7aQfxIwBH04PSvgWvpf9inx42q+E7/4fXs2ZdIm8+yDHrbykkqPXbIGP/bRRUyRUWe20UUVJQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFRXt5Bp1nNqF022K3iaSRvRVBJ/QUAfHn7THitvFvxp1iVZS0OnOun24P8ACIuHH/f0yfnXB1JdX9zq13Nq162ZruZ55ie7uxZj+ZNR1oZhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABXefsz+K28JfGnR5WlKw6i7afcAfxCXhB/wB/RH+VcHUlrf3Ok3cOrWbYmtJknhI7OjBl/UCgD9AKKjsry31Gzh1C0fdFcRLJG3qrAEfoakrM0CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigArmvjLe/2d8I/E94Dhl0C7CEHoxiYD9SK6WuN/aFLD4JeJtv8A0C3/AJihbgfFoAAwO1FFFaGYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUEAjB70UUAfb/wAGr06j8I/DF4xyzaBaBz6sIlB/UV0tcb+z1u/4Ul4Z3f8AQLT+ZrsqzNFsFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABXMfGuyOofB7xRbAZP9g3TKPUrEzD9RXT1X1XToNY0u50i6/wBXdW7wyf7rKVP86APgMHIzRSvbXFnI1ldoVlhYxyqezKcEfmKStDMKKKKACiiigAooooAKKKKACiiigAooooAKCcDNFKltcXki2VohaWZhHEo7sxwB+ZoA+3PgnZHT/g94XtiOf7BtWYehaJWP6munqvpWnQaPpdtpFt/q7S3SGP8A3VUKP5VYrM0CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA+L/wBofws3hH4za7YCMrFdXX263JGAyzDzDj2Dl1/4DXF19F/tueBGutK0v4k2UOWs3+w6gwH/ACyc7omPoFfcv1lFfOlWtiHuFFFFMQUUUUAFFFFABRRRQAUUUUAFFFFABXafs8eFm8XfGbQrAxlorW6+3XBAyFWEeYM+xcIv/Aq4uvov9iPwI1rpWqfEi8hw14/2GwJH/LJDulYeoZ9q/WI0nsNbnvNFFFQWFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBneLfDGl+NfDN94T1qPda6hbNDLjquRww9GU4IPYgV8OeLPC2r+CPE194R16Lbd2FwYpcAgOOquuf4WUhh7MK+9K8f/as+CM3jvRV8d+FrEyaxpkJFxBGPmu7YZJUDu6ckDqQWHJ2imnYTVz5bopFYMAynIPQ0tWQFFFFABRRRQAUUUUAFFFFABRRSMwUFmOAOpoA0fCfhbV/G/iax8I6DFuu9QuBFESMhB1Z2x/CqgsfZTX3H4S8MaX4L8M2PhPRY9trYWywxZHLYHLH/AGmOST3JNeYfsp/BGbwJojeO/FNl5esanCBbwSD5rO2OCFI7O/BYdQAo4O4V7BUN3LSCiiikMKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAo6ciiigD59/aR/ZkuJ7i4+Inwz04yNITLqmjwL8zN1MsIHUnqyDknkc8H59BBGRX6CV5d8Zf2XfCfxLlm8Q+H5U0jW5CWknSPMN03/TVB0Yn+NeeckNwKpMlo+TKK6Hx/wDCnx/8Mbkw+MfD0sEO7bHfxDzLaT0xIOBn+62G9q56qJCiiigAooooAKKK6HwB8KfH/wATrkQ+DvD0s8O7bJfyjy7aP1zIeDj+6uW9qAOeJAGTX0F+zd+zJcQXFv8AET4macY2jIl0vR50+ZW6iWYHoR1VD0PJ54HY/Br9l3wn8NZYfEPiCRNX1uMho53jxBat/wBMkPVgf4254yAvIr1GpbKSDryaKKKkoKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigBssUVxC1vPErxupV0dcqwPUEHqK8/8WfsufBfxY7T/wDCL/2ZO/WbR5TBj/tnzH/47XoVFAHger/sLadJIzeH/iVcQp/Cl9pqyn8WR0/lWJP+w543R8W3jrSZF9Xt5UP5DNfS9FO7FZHzRB+w543d8XPjrSY19Ut5XP5HFbekfsLadHIreIPiVcTJ/EljpqxH8Gd3/lXvlFF2Fkee+E/2XPgv4UZJ/wDhF/7TnQ8T6xKZ8/8AbPiP/wAdr0CKKK3hW3giVI0UKiIuFUDoAB0FOopDCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiior2+stMs5NQ1K8it7eFd0s88gREHqWPAFAEtFeR+PP2xvht4aL2fhO3n8QXSnG63PlWwPvKwy31RWB9a8f8Y/tW/GPxYXhs9ai0a2bjydKi2vj3lbL591K/SmkxXR9Z6trWjaBaG/17V7WxgB5mvLhYkH4sQK4rXP2n/gdoTNFJ45iu5F6Jp1tJcBvo6KU/8AHq+PtRvr7V7xtR1i/nvLhvvXF3M0sjfVmJJqKnyi5j6e1D9t34Z2+V07wxr1yR0Ywwxqfzlz+lZU37dWkhsW3w0u2HrJqaKf0Q187UU7IV2fQ3/Dddl/0TGb/wAG6/8Axqj/AIbrsv8AomM3/g3X/wCNV880UWQXZ9Df8N12X/RMZv8Awbr/APGqP+G67L/omM3/AIN1/wDjVfPNFFkF2fQ3/Dddl/0TGb/wbr/8ao/4brsv+iYzf+Ddf/jVfPNFFkF2fQ3/AA3XZf8ARMZv/Buv/wAao/4brsv+iYzf+Ddf/jVfPNFFkF2fRMX7dWllv3/wzulHqmqI380Fadh+3B8OJsLqXhLXrcn+KOOCRR/5EB/SvmOiiyC7PsHRf2qfgbrRWM+MTZSN/BqFlLEB9XK7B/31XbaH4l8OeJ7c3fhrxBY6jEOsljdpKo/FSa+CKdbTT2V0t7ZTyQTocpPC5R1PswwRS5R8x+gVFfHXg/8Aad+M3g8rGPFJ1S3Xrb6ynn5/7aZEn/j2PavXfAv7afgjWSln470a40WY8G5izcW5PqSoDrk/7JA7tSsx3R7RRVXRdc0XxJpyav4e1e2vrWT7lxaTLIh9sqevtVqkMKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACgkKCzEAAZJJ6VkeN/Hfhb4daBJ4k8XaoltbJ8qDq8z9kRerMfQe5OACa+V/jL+0f4w+K0kukWTSaXoROF0+KT57geszD73rsHyjvuIzTSuJux698Vv2vfCPhFpdG8AxR65qK5VrgOfskLe7DmU+ycf7QPFfPPjv4meOfiXe/bPGfiGa7VW3Q2o+SCH/cjHyg9txyx7k1hAY4FFUkkS22FFFFMQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBp+FPGXizwLqf9seDvEFzp1wSN7W7/LJjoHQ5Vx7MCK97+Fn7Z2l6i0ejfFawSwmOFXVrNGMDH/ponLR/Ubl5ydor5xopWTGnY+/7K9stSs49Q028iuLeZA8M8EgdJFPQqw4I9xUtfFPwp+Nnjf4RXwbQLz7Rp7vuutIuXJhkz1K/wDPN/8AaX2yGAxX1Z8K/jD4O+LmjnUPDl0Y7qFR9t02cgTW59x/Ep7MOD7EECWrFJ3OqooopDCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigArmfit8VvDPwj8NNr+vuZJZCUsLCJgJLqTH3R6KOrMeFHqSAdDxz420H4d+Frvxd4kuCltapnavLyueFjQd2Y4A/M4AJr4u+I3xD8RfFHxVP4r8Ry/O/y21srZS1iz8sa/Tue5yaaVxN2D4ifEfxX8UfEL+I/Fd7vcZW2to8iK1Q/wIvbtk9Tjk1hUUVZAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVd8OeI9d8I63b+I/DOpyWd7atuhniP5qQeGU9Cp4I61SooA+w/gR8e9G+MOlmzu0jstdtYwb2wDfLIvTzYs8lM9R1UnBzkM3oNfA2g69rPhfWrbxF4e1B7W9s5RJbzx9VPoR0IIyCDwQSDwa+yfgp8XNL+MHg9NbgRIL+3Ii1WyVv8AUy46jPOxuqn6jqpqGrFpnYUUUUhhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFcd8e/H0nw4+FmqeILOfy72SMWunEHkTyHaGHuo3P/wCgD59/ao+LUnxB8cN4Y0m63aRoczRRbW+We5HyyS+4HKL7BiD81eXUiqFUKO1LWhmFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAV1fwX+J938JvHlt4lV3axkIg1aBRnzLcnkgd2U/MPoR0Y1ylFAH6A29xb3dvHd2k6yxSoHikRsq6kZBBHUEU+vK/2QfHEnir4VLoV7NuudBuDafM2WMBG6I/QAlB/1zr1Ss9jQKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAr5+/bn8RNs8O+EIpvlZ5724j9CoEcZ/8elr6Br5J/a91w6v8bbqyz8ul6fbWgx6lTMf/AEdj8Ka3E9jzGiiirICiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAPaf2INcaz8f6x4dL4S/wBJWbBPV4ZAB+kzflX03Xxr+zTrI0T446BPI+I7ieS1k56+ZE6qP++9n5V9lVD3LjsFFFFIYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAA5OK+G/ixrP/CQfFHxFrAk3rLrVwIm9Y1kKJ/46or7d1TUYNH0u51a5/1drbvNJz/Cqlj/ACr4BSSWZRNO2Xf5nPqTyf1qokyFoooqiQooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigDQ8I6v/AMI94u0nxATgWGqW9wfokqsf0Ffeh61+fM6b4XT1Uj9K+9fCGrnxB4S0rXy2TfabBcZ9d8at/WpkVE0aKKKkoKKKKACiiigAooooAKKKKACiiigAooooAKKKKAOV+OOpDSfg54nvM4J0S4iQ+jOhQfqwr4lHHAr6/wD2r7v7L8BtaAbDTSWsa++bmLP6A18gVUdiZBRRRVEhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABX2l+z3qX9q/BPwzcZz5elJB/36zH/wCyV8W19efslXYufgPpMXeC4u4z/wCBMjD9GFTIqO56RRRRUlBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB5R+2ZcGH4NeSD/rtXtkP4bm/9lr5Sr6m/bWz/wAKktMf9B6DP/fqavlmrjsQ9wooopiCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACvqv9jGcy/Bxoif8AVazcKPxCN/7NXypX1N+xSD/wqO6J769Pj/v1DUy2KjuevUUUVJQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAeWftjWTXXwVmuQOLXU7WQ+2X8v8A9nr5Or7U/aA0CTxL8GPEWmQqWddONwijqzQsJgB7kx4r4rBBGQaqOxEtwoooqhBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABX1j+x1ZtbfBSC4I/4+dTupB74fZ/7JXycSAMmvtH9nnQ5PD3wU8OafKCGk08XLKexmZpsf+RKmWxUdzs6KKKkoKKKKACiiigAooooAKKKKACiiigAooooAKKKKAEZEkUxyIGVhhlYZBHcV8R/F/4b3vwq8e3nhWeJha7zLpczdJbZj8nPcr91vdT2Ir7drnfib8LvCnxX8PHQPFFqcoS1peQ4Ets/95D/ADB4PcdKadhNXPh2iuu+LHwV8afCHUTHrtt9o06STbaavbofJl9A3/PN/wDZPocFgM1yNWQFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUVo+FfCfiLxxrsPhrwrpcl3eTn5Y06Ivd3PRVGeSf5kCgC58M/Ad98TPHOn+DLJH23UwN5Kn/ACxt1OZHz2wvA9WKjvX3LDDDbQpb28SpHGoWNFGAqgYAH4VxPwP+CWi/BvQGhSRbvVrtQdS1DbjcR0jTPSMfmTyewHcVDdy0rBRRRSGFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBDf2FhqtlLpuqWMNzbToUmt7iIOkinsyngj614b8Uf2L9OvjJq/wp1FbKQ5Y6RfOTC3tHJyyfRtw56qK94ooTsG58HeLPBfizwJqP8AZPjHw9c6dOSQguE+STHdHGVce6k1mV996to+ka/YPpWu6VbXtrJ/rLe7hWRG+qsCK8l8c/sYfD7Xi954L1O50K4bkQ83FsT/ALjEMv4PgelVzEuJ8vUV6J4x/ZZ+MnhHfNDoCavbr/y30eTzGx7xkCTPsFP1rz67trnT7t9P1G1lt7iM4kt7iMpIv1VgCKokZRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUVNp2n6hrN8umaNp9xeXT/ctrSBpZG+iqCTQBDSMyoNzMAB1Jr1XwN+yF8VPFRS58QJBoFo2CWvT5k5HqIkPH0ZlPtXt/w4/Zn+F3w6ePUI9LbVNRjIYX+qYkKN6omNiYPQgbh/eNJtDszwL4Ufsy/ED4lmLU72BtG0h8H7deRHzJV/6ZRHBbPZjhe4LYxX078Ofhf4N+Fmjf2N4Q03y9+Dc3cpDT3LD+J3wM98AYUZOAK6EknrRUt3KSsFFFFIYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABVHX/C/hrxXaix8UeHrHUYR0jvrVJQPcbgcGr1FAHl3iT9kD4M66TJpthfaRIcktp16SpP+5KHUD2AFcH4g/YZ16HL+FPiBaXGT8sWpWbQ4+roXz/3yK+jaKd2KyPj3W/2WPjlohYr4RS/jXrLp19E4P0Virn/vmuS1jwL458PKX1/wVq9kq9ZLrTJUT/vorg/nX3fRk+tPmFyn58rPC5wkqn2DU6vvXV/C3hjxBxr/AIb0++9ftllHL/6EDXO6n+z78E9WJNz8M9Kjz1+yQeR/6KK0cwcp8WUV9c337I/wKux+48M3VqfWDVpz+juwrKuP2JvhNMSYdb8QQegjvISP/HoTT5kLlZ8t0V9LXH7DfgZs/ZPHOtJ6easD/wAkFVJP2FtFP+p+JN4v+/pyH+TCi6CzPnSivob/AIYUsv8Aop8//goX/wCOU5f2FdPz8/xNuD/u6Uo/9qUXQWZ870V9Hw/sMeGR/wAfHxD1Jv8ArnaRL/PNXbf9h74aoP8ASvF3iGQ/7E1uo/8ARJougsz5jor6usf2NfgzakG5TVrvHafUiuf+/arWxY/swfAnT2DReAIpCP8An5vJ5QfwdyP0pcyHys+OGdEGXYD6mrOk6RrHiCXydA0e8v3zjZY2rzH8kBr7f0r4XfDPQ2V9H+HuiWzr0kh0uIN/31tzW6oCKEQYAGABwBRzBynxjoX7Ofxt8QhZLT4fXcEZ6yag6W236rIwb8hXb+Hv2HvGl2Q/inxpptgvXZZQvct9Pm8sA/nX0vRS5mOyPKfC/wCx18INDKzazHf6zKME/brrZHn2SILkezFq9I0Dwz4c8KWf9neGNAs9OgzkxWVssSk+pCgZPuavUUhhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAf/2Q==";
    }
    $errors = $user->register($name, $pseudo, $password, $email, $bio, $picture);
    if(isset($errors) && strlen($errors) == 41) {
        $usernameError = $errors;
    }else if(isset($errors) && strlen($errors) == 40) {
        $mailError = $errors;
    }
}



include('./homepc.php');
?>

    <div class="mainRegister">
        <div class="header">
            <div class="headerLogo">
                <a href="index.php">
                    <img src="assets/img/bbcLogo.svg" alt="photo du logo">
                </a>
            </div>

            <div class="headerTitle">
                <h1>CRÉER UN COMPTE</h1>
            </div>
        </div>

        <div class="registerContent">
            <form action="" method="post" class="formRegister" enctype="multipart/form-data">

                <h2>ENTREZ VOS COORDONNÉS</h2>
                <input class="ipRegister" type="text" name="nom" placeholder="Nom" required>
                <input class="ipRegister" type="text" name="username" placeholder="Nom d'utilisateur" required>
              
                <p class="error">
                <?php 
                if(isset($usernameError)) {
                    echo $usernameError;
                }?>
                </p>
                <h2>ENTREZ VOTRE MOT DE PASSE</h2>
                <input class="ipRegister" type="password" name="password" placeholder="Mot de passe" required>

                <h2>ENTREZ VOTRE EMAIL</h2>
                <input class="ipRegister" type="email" name="email" placeholder="Email" required>
               
                <p class="error">
                <?php 
                if(isset($mailError)) {
                    echo $mailError;
                }?>
                </p>
                <p class="infonMail">Ajoutez votre adresse e-mail pour recevoir des notifications sur votre activité sur Foundation. Cela ne sera pas affiché sur votre profil.</p>

                <h2>ENTREZ VOTRE BIOGRAPHIE</h2>
                <textarea class="txtRegister" type="text" name="bio" placeholder="Entrez votre bio ici"></textarea>

                
                <h2>TÉLÉCHARGEZ UNE IMAGE DE PROFIL</h2>
                
                <label for="addPic" class="labelPic">
                    <div class="labelContent">
                    <img class='uploadImg'src="assets/img/imagefile.svg" alt="icon pour déposer une photo" draggable="false" enctype="multipart/form-data">
                    <h3>Glisser-déposer ou parcourir un fichier</h3>
                    <h4 style="text-align: center ;">Taille recommandée: JPG, PNG, GIF <br> (150x150px, Max 10mb)</h4>
                    </div>

                    <div class="hiddenContent none">
                        <img src="assets/img/plus-solid.svg" alt="icon de plus" draggable="false">
                    </div>
                    <div class="hiddenContent2 none">
                        <img src="" alt="icon de plus" draggable="false" class='check-false'>
                        <h2 class="nameImg"></h2>
                    </div>
                  
                
                    <input type="file" name="profilePic" id="addPic" style="display:none;"  accept=".JPG, .PNG, .GIF" >
                </label>

                <input class='submitRegister' type="submit" name="register" value="CRÉER UN COMPTE">
            </form>
        </div>

    </div>


    <script src="assets/js/file.js"></script>

<?php include('footer.php');?>
